// <auto-generated> - Template:RepositoryInterfaceCrud, Version:1.1, Id:387dfdc5-b9f2-4ab4-accb-00a22cdd916c
using CodeGenHero.Repository;
using CodeGenHero.ResourceScheduler.Repository.Entities.RS;
using System.Linq;

namespace CodeGenHero.ResourceScheduler.Repository.Interface
{
	public interface IRSRepositoryCrud : 
		ICRUDOperation<Resource>,
		ICRUDOperation<ResourceSchedule>,
		ICRUDOperation<User>
	{

		#region GetQueryable

		IQueryable<Resource> GetQueryable_Resource();
		IQueryable<ResourceSchedule> GetQueryable_ResourceSchedule();
		IQueryable<User> GetQueryable_User();

		#endregion

	}
}
