// <auto-generated> - Template:RepositoryInterface, Version:1.1, Id:f766650e-5c46-4239-b6fd-0cfca2673207
using CodeGenHero.Repository;
using CodeGenHero.ResourceScheduler.Repository.Entities.RS;
using System;
using System.Threading.Tasks;

namespace CodeGenHero.ResourceScheduler.Repository.Interface
{
	public partial interface IRSRepository : IRSRepositoryCrud
	{

		RSDataContext RSDataContext { get; }

		Task<IRepositoryActionResult<Resource>> Delete_ResourceAsync(System.Guid id);
		Task<Resource> Get_ResourceAsync(System.Guid id, int numChildLevels);

		Task<IRepositoryActionResult<ResourceSchedule>> Delete_ResourceScheduleAsync(System.Guid id);
		Task<ResourceSchedule> Get_ResourceScheduleAsync(System.Guid id, int numChildLevels);

		Task<IRepositoryActionResult<User>> Delete_UserAsync(System.Guid id);
		Task<User> Get_UserAsync(System.Guid id, int numChildLevels);

	}
}
