// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CodeGenHero.ResourceScheduler.Model.RS.Interface
{
	public partial interface IUser
	{
		string CreatedBy { get; }
		System.DateTime CreatedDate { get; }
		string Email { get; }
		System.Guid Id { get; }
		string InstallationId { get; }
		bool IsActive { get; }
		bool IsDeleted { get; }
		System.DateTime? LastLoginDate { get; }
		string Name { get; }
		string UpdatedBy { get; }
		System.DateTime UpdatedDate { get; }
		string UserName { get; }

		List<IResourceSchedule> ResourceSchedules { get; }


	}
}
