// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace CodeGenHero.ResourceScheduler.DTO.RS
{
	public partial class User
	{
		public User()
		{
			InitializePartial();
		}

		public System.Guid Id { get; set; } // Primary key
		public string CreatedBy { get; set; }
		public System.DateTime CreatedDate { get; set; }
		public string Email { get; set; }
		public string InstallationId { get; set; }
		public System.DateTime? LastLoginDate { get; set; }
		public bool IsActive { get; set; }
		public bool IsDeleted { get; set; }
		public string UpdatedBy { get; set; }
		public System.DateTime UpdatedDate { get; set; }
		public string Name { get; set; }
		public string UserName { get; set; }
		public virtual System.Collections.Generic.ICollection<ResourceSchedule> ResourceSchedules { get; set; } // Many to many mapping


		partial void InitializePartial();

	}
}
