// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CodeGenHero.ResourceScheduler.Repository.Entities.RS
{

    // ResourceSchedule
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ResourceSchedule
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public System.Guid ResourceId { get; set; } // ResourceID
        public string CreatedBy { get; set; } // CreatedBy (length: 150)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public bool IsDeleted { get; set; } // IsDeleted
        public string UpdatedBy { get; set; } // UpdatedBy (length: 150)
        public System.DateTime UpdatedDate { get; set; } // UpdatedDate
        public System.DateTime ReservationStartDateTime { get; set; } // ReservationStartDateTime
        public System.DateTime ReservationEndDateTime { get; set; } // ReservationEndDateTime
        public string ReservationNotes { get; set; } // ReservationNotes (length: 255)
        public System.Guid? ReservedByUserId { get; set; } // ReservedByUserId
        public string ReservedForUser { get; set; } // ReservedForUser (length: 150)
        public System.DateTime ReservedOnDateTime { get; set; } // ReservedOnDateTime

        // Foreign keys

        /// <summary>
        /// Parent Resource pointed by [ResourceSchedule].([ResourceId]) (FK_ResourceSchedule_Resource)
        /// </summary>
        public Resource Resource { get; set; } // FK_ResourceSchedule_Resource

        /// <summary>
        /// Parent User pointed by [ResourceSchedule].([ReservedByUserId]) (FK_ResourceSchedule_User)
        /// </summary>
        public User User { get; set; } // FK_ResourceSchedule_User

        public ResourceSchedule()
        {
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
