// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CodeGenHero.ResourceScheduler.Repository.Entities.RS
{

    // Resource
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Resource
    {
        public System.Guid Id { get; set; } // ID (Primary key)
        public string CreatedBy { get; set; } // CreatedBy (length: 150)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string Description { get; set; } // Description (length: 255)
        public string ImageLink { get; set; } // ImageLink (length: 255)
        public string ImageLinkThumb { get; set; } // ImageLinkThumb (length: 255)
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string UpdatedBy { get; set; } // UpdatedBy (length: 150)
        public System.DateTime UpdatedDate { get; set; } // UpdatedDate
        public string Name { get; set; } // Name (length: 150)

        // Reverse navigation

        /// <summary>
        /// Child ResourceSchedules where [ResourceSchedule].[ResourceID] point to this entity (FK_ResourceSchedule_Resource)
        /// </summary>
        public System.Collections.Generic.ICollection<ResourceSchedule> ResourceSchedules { get; set; } // ResourceSchedule.FK_ResourceSchedule_Resource

        public Resource()
        {
            IsActive = true;
            IsDeleted = false;
            ResourceSchedules = new System.Collections.Generic.List<ResourceSchedule>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
