// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace CodeGenHero.ResourceScheduler.Xam.ModelObj.RS
{
    
    public partial class ResourceSchedule : ObservableObject
	{
        
        public ResourceSchedule()
		{
			InitializePartial();
		}

		private string _createdBy;
		private System.DateTime _createdDate;
		private System.Guid _id;
		private bool _isDeleted;
		private System.DateTime _reservationEndDateTime;
		private string _reservationNotes;
		private System.DateTime _reservationStartDateTime;
		private System.Guid? _reservedByUserId;
		private string _reservedForUser;
		private System.DateTime _reservedOnDateTime;
		private System.Guid _resourceId;
		private string _updatedBy;
		private System.DateTime _updatedDate;


		public string CreatedBy
		{
			get { return _createdBy; }
			set
			{
				Set<string>(() => CreatedBy, ref _createdBy, value);
				RunCustomLogicSetCreatedBy(value);
			}
		}

		public System.DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				Set<System.DateTime>(() => CreatedDate, ref _createdDate, value);
				RunCustomLogicSetCreatedDate(value);
			}
		}

		public System.Guid Id
		{
			get { return _id; }
			set
			{
				Set<System.Guid>(() => Id, ref _id, value);
				RunCustomLogicSetId(value);
			}
		}

		public bool IsDeleted
		{
			get { return _isDeleted; }
			set
			{
				Set<bool>(() => IsDeleted, ref _isDeleted, value);
				RunCustomLogicSetIsDeleted(value);
			}
		}

		public System.DateTime ReservationEndDateTime
		{
			get { return _reservationEndDateTime; }
			set
			{
				Set<System.DateTime>(() => ReservationEndDateTime, ref _reservationEndDateTime, value);
				RunCustomLogicSetReservationEndDateTime(value);
			}
		}

		public string ReservationNotes
		{
			get { return _reservationNotes; }
			set
			{
				Set<string>(() => ReservationNotes, ref _reservationNotes, value);
				RunCustomLogicSetReservationNotes(value);
			}
		}

		public System.DateTime ReservationStartDateTime
		{
			get { return _reservationStartDateTime; }
			set
			{
				Set<System.DateTime>(() => ReservationStartDateTime, ref _reservationStartDateTime, value);
				RunCustomLogicSetReservationStartDateTime(value);
			}
		}

		public System.Guid? ReservedByUserId
		{
			get { return _reservedByUserId; }
			set
			{
				Set<System.Guid?>(() => ReservedByUserId, ref _reservedByUserId, value);
				RunCustomLogicSetReservedByUserId(value);
			}
		}

		public string ReservedForUser
		{
			get { return _reservedForUser; }
			set
			{
				Set<string>(() => ReservedForUser, ref _reservedForUser, value);
				RunCustomLogicSetReservedForUser(value);
			}
		}

		public System.DateTime ReservedOnDateTime
		{
			get { return _reservedOnDateTime; }
			set
			{
				Set<System.DateTime>(() => ReservedOnDateTime, ref _reservedOnDateTime, value);
				RunCustomLogicSetReservedOnDateTime(value);
			}
		}

		public System.Guid ResourceId
		{
			get { return _resourceId; }
			set
			{
				Set<System.Guid>(() => ResourceId, ref _resourceId, value);
				RunCustomLogicSetResourceId(value);
			}
		}

		public string UpdatedBy
		{
			get { return _updatedBy; }
			set
			{
				Set<string>(() => UpdatedBy, ref _updatedBy, value);
				RunCustomLogicSetUpdatedBy(value);
			}
		}

		public System.DateTime UpdatedDate
		{
			get { return _updatedDate; }
			set
			{
				Set<System.DateTime>(() => UpdatedDate, ref _updatedDate, value);
				RunCustomLogicSetUpdatedDate(value);
			}
		}

		public virtual Resource Resource { get; set; } 
		public virtual User User { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetCreatedBy(string value);
		partial void RunCustomLogicSetCreatedDate(System.DateTime value);
		partial void RunCustomLogicSetId(System.Guid value);
		partial void RunCustomLogicSetIsDeleted(bool value);
		partial void RunCustomLogicSetReservationEndDateTime(System.DateTime value);
		partial void RunCustomLogicSetReservationNotes(string value);
		partial void RunCustomLogicSetReservationStartDateTime(System.DateTime value);
		partial void RunCustomLogicSetReservedByUserId(System.Guid? value);
		partial void RunCustomLogicSetReservedForUser(string value);
		partial void RunCustomLogicSetReservedOnDateTime(System.DateTime value);
		partial void RunCustomLogicSetResourceId(System.Guid value);
		partial void RunCustomLogicSetUpdatedBy(string value);
		partial void RunCustomLogicSetUpdatedDate(System.DateTime value);

		#endregion RunCustomLogicSet

	}
}
