// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace CodeGenHero.ResourceScheduler.Xam.ModelObj.RS
{
	public partial class User : ObservableObject
	{
		public User()
		{
			ResourceSchedules = new System.Collections.Generic.List<ResourceSchedule>(); // Reverse Navigation

			InitializePartial();
		}

		private string _createdBy;
		private System.DateTime _createdDate;
		private string _email;
		private System.Guid _id;
		private string _installationId;
		private bool _isActive;
		private bool _isDeleted;
		private System.DateTime? _lastLoginDate;
		private string _name;
		private string _updatedBy;
		private System.DateTime _updatedDate;
		private string _userName;


		public string CreatedBy
		{
			get { return _createdBy; }
			set
			{
				Set<string>(() => CreatedBy, ref _createdBy, value);
				RunCustomLogicSetCreatedBy(value);
			}
		}

		public System.DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				Set<System.DateTime>(() => CreatedDate, ref _createdDate, value);
				RunCustomLogicSetCreatedDate(value);
			}
		}

		public string Email
		{
			get { return _email; }
			set
			{
				Set<string>(() => Email, ref _email, value);
				RunCustomLogicSetEmail(value);
			}
		}

		public System.Guid Id
		{
			get { return _id; }
			set
			{
				Set<System.Guid>(() => Id, ref _id, value);
				RunCustomLogicSetId(value);
			}
		}

		public string InstallationId
		{
			get { return _installationId; }
			set
			{
				Set<string>(() => InstallationId, ref _installationId, value);
				RunCustomLogicSetInstallationId(value);
			}
		}

		public bool IsActive
		{
			get { return _isActive; }
			set
			{
				Set<bool>(() => IsActive, ref _isActive, value);
				RunCustomLogicSetIsActive(value);
			}
		}

		public bool IsDeleted
		{
			get { return _isDeleted; }
			set
			{
				Set<bool>(() => IsDeleted, ref _isDeleted, value);
				RunCustomLogicSetIsDeleted(value);
			}
		}

		public System.DateTime? LastLoginDate
		{
			get { return _lastLoginDate; }
			set
			{
				Set<System.DateTime?>(() => LastLoginDate, ref _lastLoginDate, value);
				RunCustomLogicSetLastLoginDate(value);
			}
		}

		public string Name
		{
			get { return _name; }
			set
			{
				Set<string>(() => Name, ref _name, value);
				RunCustomLogicSetName(value);
			}
		}

		public string UpdatedBy
		{
			get { return _updatedBy; }
			set
			{
				Set<string>(() => UpdatedBy, ref _updatedBy, value);
				RunCustomLogicSetUpdatedBy(value);
			}
		}

		public System.DateTime UpdatedDate
		{
			get { return _updatedDate; }
			set
			{
				Set<System.DateTime>(() => UpdatedDate, ref _updatedDate, value);
				RunCustomLogicSetUpdatedDate(value);
			}
		}

		public string UserName
		{
			get { return _userName; }
			set
			{
				Set<string>(() => UserName, ref _userName, value);
				RunCustomLogicSetUserName(value);
			}
		}

		public virtual System.Collections.Generic.IList<ResourceSchedule> ResourceSchedules { get; set; } // Many to many mapping


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetCreatedBy(string value);
		partial void RunCustomLogicSetCreatedDate(System.DateTime value);
		partial void RunCustomLogicSetEmail(string value);
		partial void RunCustomLogicSetId(System.Guid value);
		partial void RunCustomLogicSetInstallationId(string value);
		partial void RunCustomLogicSetIsActive(bool value);
		partial void RunCustomLogicSetIsDeleted(bool value);
		partial void RunCustomLogicSetLastLoginDate(System.DateTime? value);
		partial void RunCustomLogicSetName(string value);
		partial void RunCustomLogicSetUpdatedBy(string value);
		partial void RunCustomLogicSetUpdatedDate(System.DateTime value);
		partial void RunCustomLogicSetUserName(string value);

		#endregion RunCustomLogicSet

	}
}
