// <auto-generated> - Template:AutoMapperProfile, Version:1.1, Id:f3f865a7-e545-4bc4-b0ba-c9e7ee587e73
using AutoMapper;
using xDTO = CodeGenHero.ResourceScheduler.DTO.RS;
using xENT = CodeGenHero.ResourceScheduler.Repository.Entities.RS;

namespace CodeGenHero.ResourceScheduler.Repository.Infrastructure
{
	public partial class RSAutoMapperProfile : Profile
	{
		public RSAutoMapperProfile()
		{
			InitializeProfile();
			InitializePartial();
		}

		partial void InitializePartial();

		private void InitializeProfile()
		{
			CreateMap<xDTO.Resource, xENT.Resource>()
				// .ForMember(d => d.ResourceSchedules, opt => opt.Ignore()) // Reverse nav
			.ReverseMap();

			CreateMap<xDTO.ResourceSchedule, xENT.ResourceSchedule>()
				// .ForMember(d => d.Resource, opt => opt.Ignore())
				// .ForMember(d => d.User, opt => opt.Ignore())
			.ReverseMap();

			CreateMap<xDTO.User, xENT.User>()
				// .ForMember(d => d.ResourceSchedules, opt => opt.Ignore()) // Reverse nav
			.ReverseMap();

		}
	}
}
