// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.ResourceScheduler.DTO.RS;

namespace CodeGenHero.ResourceScheduler.DTO.RS
{
	public static class DemoResourceSchedule
	{
		public static System.Guid SampleResourceScheduleId00 = Guid.Parse("f8c457bd-10b9-4a84-a4b5-ef360dfb4dce");
		public static System.Guid SampleResourceScheduleId01 = Guid.Parse("349c3f92-2bbf-46d4-abdc-ed9994b7cb20");

		public static ResourceSchedule SampleResourceSchedule00
		{
			get
			{
				return new ResourceSchedule()
				{
					Id = SampleResourceScheduleId00,
					ResourceId = Guid.Parse("716f56f8-fe2a-46c2-adfb-dd777a0a30a1"),
					CreatedBy = "SampleCreatedBy",
					CreatedDate = DateTime.Now,
					IsDeleted = false,
					UpdatedBy = "SampleUpdatedBy",
					UpdatedDate = DateTime.Now,
					ReservationStartDateTime = DateTime.Now,
					ReservationEndDateTime = DateTime.Now,
					ReservationNotes = "SampleReservationNotes",
					ReservedByUserId = Guid.Parse("c8a557bf-7ff9-4980-82af-2c79a5010325"),
					ReservedForUser = "SampleReservedForUser",
					ReservedOnDateTime = DateTime.Now,
				};
			}
		}
		public static ResourceSchedule SampleResourceSchedule01
		{
			get
			{
				return new ResourceSchedule()
				{
					Id = SampleResourceScheduleId01,
					ResourceId = Guid.Parse("8ad0340c-ef31-4fc1-9d37-9ffd9ec741e8"),
					CreatedBy = "SampleCreatedBy",
					CreatedDate = DateTime.Now,
					IsDeleted = false,
					UpdatedBy = "SampleUpdatedBy",
					UpdatedDate = DateTime.Now,
					ReservationStartDateTime = DateTime.Now,
					ReservationEndDateTime = DateTime.Now,
					ReservationNotes = "SampleReservationNotes",
					ReservedByUserId = Guid.Parse("10f7ac96-a8bd-497d-b3f3-97b929f531d2"),
					ReservedForUser = "SampleReservedForUser",
					ReservedOnDateTime = DateTime.Now,
				};
			}
		}

	}
}
