// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.ResourceScheduler.DTO.RS;

namespace CodeGenHero.ResourceScheduler.DTO.RS
{
	public static class DemoUser
	{
		public static System.Guid SampleUserId00 = Guid.Parse("ccbdd668-337a-4b3d-9aff-9f1c86aab641");
		public static System.Guid SampleUserId01 = Guid.Parse("31d34efa-d592-4bdf-8f00-a11a4490d3ef");

		public static User SampleUser00
		{
			get
			{
				return new User()
				{
					Id = SampleUserId00,
					CreatedBy = "SampleCreatedBy",
					CreatedDate = DateTime.Now,
					Email = "SampleEmail",
					InstallationId = "SampleInstallationId",
					LastLoginDate = DateTime.Now,
					IsActive = false,
					IsDeleted = false,
					UpdatedBy = "SampleUpdatedBy",
					UpdatedDate = DateTime.Now,
					Name = "SampleName",
					UserName = "SampleUserName",
				};
			}
		}
		public static User SampleUser01
		{
			get
			{
				return new User()
				{
					Id = SampleUserId01,
					CreatedBy = "SampleCreatedBy",
					CreatedDate = DateTime.Now,
					Email = "SampleEmail",
					InstallationId = "SampleInstallationId",
					LastLoginDate = DateTime.Now,
					IsActive = false,
					IsDeleted = false,
					UpdatedBy = "SampleUpdatedBy",
					UpdatedDate = DateTime.Now,
					Name = "SampleName",
					UserName = "SampleUserName",
				};
			}
		}

	}
}
